dist: trusty
language: java
sudo: required

script:
    - ./gradlew checkSourceFormatting

after_success:
    - git archive --format=zip HEAD > com-liferay-osb-pulpo-engine-contacts-deployment-private.zip