language: java
dist: trusty
sudo: required
cache:
  directories:
  - "${HOME}/bin"

# Install terraform
install:
    - pushd "${TMPDIR}" ;
    - curl -sSL -o terraform.zip "https://releases.hashicorp.com/terraform/0.10.7/terraform_0.10.7_linux_amd64.zip" ;
    - unzip terraform.zip ;
    - mv -v terraform "${HOME}/bin/terraform" ;
    - chmod +x "${HOME}/bin/terraform" ;
    - popd ;
    - terraform version ;

script:
    - ./gradlew checkSourceFormatting

after_success:
    - git archive --format=zip HEAD > com-liferay-osb-pulpo-engine-contacts-deployment-private.zip