version: 0.2

phases:
  install:
    commands:
      - echo install phase started on `date`
  pre_build:
    commands:
      - echo pre_build phase started on `date`
  build:
    commands:
      - echo build phase started on `date`
      - gradle -version
  post_build:
    commands:
      - echo post_build phase completed on `date`