branch-defaults:
  default:
    environment: pulpo-engine-contacts-dev
    group_suffix: null
global:
  application_name: pulpo-engine-contacts
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Multi-container Docker 17.03.1-ce (Generic)
  default_region: eu-west-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application