################## Filebeat Pulpo Connector DE Configuration ##################

# This file is the configuration file for the filebeat running inside this
# beanstalk docker instance

#==========================  Modules configuration ============================

filebeat.prospectors:

#------------------------------ Log prospector --------------------------------
- input_type: log

  paths:
    - /var/log/aws/*.log
    - /var/log/aws/containers/*.log

  multiline.pattern: '^%{TIME}'

  multiline.negate: false

  multiline.match: after

#================================ General ======================================

tags: '${PULPO_CONTACTS_ENGINE_BEAT_TAGS}'

fields:
  env: '${PULPO_CONTACTS_ENGINE_BEAT_ENV}'
  service: '${PULPO_CONTACTS_ENGINE_BEAT_SERVICE}'

#================================ Outputs ======================================

#-------------------------- Elasticsearch output -------------------------------
output.elasticsearch:
  hosts: '${PULPO_CONTACTS_ENGINE_BEAT_ES_HOSTS}'

#================================ Logging ======================================
logging.level: info

logging.to_files: true
